CO-725: Meta XE API frontend application
osu-mist/meta-xe-frontend pull request #1
Opened 2017-03-21 20:43 UTC by magical

Adapted from the OAuth2 consent demo app

2017-03-21 21:46 UTC, jaredkosanovic requested changes
Overall great work. I tested this by running it in a container and it looks great and functions well.

2017-03-21 21:46 UTC, jaredkosanovic commented on Dockerfile
> +MAINTAINER Andrew Ekstedt <ekstedta@oregonstate.edu>
Could you use [LABEL](https://docs.docker.com/engine/reference/builder/#label) here instead? https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

2017-03-21 21:46 UTC, jaredkosanovic commented on README.md
> +Meta XE Frontend
Could you add a config.py example file to this repo?

2017-03-21 21:46 UTC, jaredkosanovic commented on Dockerfile
> +FROM python:2.7-alpine
Could you add a [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) to this image?

2017-03-21 21:46 UTC, jaredkosanovic commented on metaxe/templates/index.html
> +
Multiple blank lines

2017-03-21 21:46 UTC, jaredkosanovic commented on metaxe/templates/index.html
> +                <button class="btn btn-primary">Filter</button>
Maybe we should add a "clear" or "reset" button around this area to make the instance set to "Any" and clear the search box.

2017-03-21 21:46 UTC, jaredkosanovic commented on requirements.txt
> +appdirs==1.4.3
As you suggested, I had to change this to appdirs==1.4.2 or else I couldn't build the docker image. It told me that 1.4.2 was already installed (maybe along with a different package?). I didn't see any issues with running 1.4.2.

2017-03-21 22:32 UTC, magical commented on Dockerfile
> +MAINTAINER Andrew Ekstedt <ekstedta@oregonstate.edu>
Huh. When was maintainer deprecated?

2017-03-21 22:51 UTC, floppyears commented
* When viewing the list of apps in any instance the distinction between the applications is not as easy on the eyes. Either adding some top & bottom margin or alternate color on the rows would help.

2017-03-21 22:51 UTC, floppyears commented on requirements.txt
> +appdirs==1.4.3
I ran into this issue as well.

2017-03-21 22:55 UTC, jaredkosanovic commented on Dockerfile
> +MAINTAINER Andrew Ekstedt <ekstedta@oregonstate.edu>
@magical https://github.com/docker/docker/pull/25466

2017-03-21 22:59 UTC, floppyears commented on metaxe/templates/index.html
> +      <a href="http://oregonstate.edu"><img id="logo" src="http://oregonstate.edu/images/logo.jpg?v=1" alt="Oregon State University" width="215" height="78"/></a>
Why not specify the width and height in css?

2017-03-21 23:17 UTC, magical commented on metaxe/templates/index.html
> +      <a href="http://oregonstate.edu"><img id="logo" src="http://oregonstate.edu/images/logo.jpg?v=1" alt="Oregon State University" width="215" height="78"/></a>
Those are from the OSU template I based this off of.

2017-03-23 17:52 UTC, jaredkosanovic approved these changes

2017-03-23 22:53 UTC, merged